[package]
name = "open-wearther-wizard"
version = "0.1.0"
edition = "2024"
authors = ["Arunkumar Mourougappane <amouroug@buffalo.edu>"]

[dependencies]
env_logger = "0.11.8"
gtk = { version = "0.10.0", package = "gtk4" }
glib = "0.21.0"
gio = { version = "0.21.0", package = "gio" }
log = { version = "0.4.27", features = ["std"] }
reqwest = { version = "0.12.23", features = ["json"] }
gdk-pixbuf = "0.21.0"
rust-embed = { version = "8.7.2", features = ["compression"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
