[package]
name = "open-wearther-wizard"
version = "0.1.0"
edition = "2024"
authors = ["Arunkumar Mourougappane <amouroug@buffalo.edu>"]

[dependencies]
glib = "0.21.1"
gtk4 = "0.10.0"
reqwest = { version = "0.12.23", features = ["json"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
tokio = { version = "1.47.1", features = ["full"] }
